### ISSUE TITLE
Pinned keystoneclient version causes dependency resolution issues

### ISSUE THREAD

**Issue by andrew-vant** [racker/eom#106]
EOM's requirements.txt specifies python-keystoneclient==1.6.0 (current version: 3.13.0). KSC 1.6.0 depends on pbr >=0.11,<2.0. Most other packages in eom and KSC's dependency trees depend on pbr>2.1 or so.

For some reason eom installs anyway if installed alone, but it's breaking RSE2's dep resolution (RSE2 depends on EOM).

To reproduce:

```
$ virtualenv venv
$ . venv/bin/activate
$ pip install eom pipdeptree
$ pipdeptree
```

`pipdeptree` should note the dependency conflict at the beginning of the output. Probably the eom deps should instead specify keystoneclient>=1.6.0,<2.0.

**Comment by BenjamenMeyer** [comment]
@andrew-vant thanks for bringing this to my attention. Not sure if I'll be able to get to it today; PRs are welcome. It'd probably be good to get requires.io setup on this repo and then pin all targets.

**Comment by andrew-vant** [comment]
Okay, done. I'm not familiar with requires.io, so this just fixes the problem at hand.
